version: '3.3'

services:
  postgres:
    image: postgres:15.1-alpine3.17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-spl-token-lending}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?postgres password is required}
      POSTGRES_DB: ${POSTGRES_DB:-dev}

  spl-token-lending-api:
    image: spl-token-lending-api:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
