"""add loan table

Revision ID: 0002
Revises: 0001
Create Date: 2023-02-02 15:52:08.826899

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan',
                    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'CLOSED', name='status'), nullable=False),
                    sa.Column('address', sa.String(), nullable=False),
                    sa.Column('amount', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan')
    # ### end Alembic commands ###
